apiVersion: apps/v1 #create controller
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
    operator: mesaque
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: gcr.io/apikihost/github-mesaque-k8s-v1-admin:3c870a5c491866c820968007d703ae2c2d82069d
          name: admin
          ports:
            - containerPort: 80
              name: admin