apiVersion: apps/v1 #create controller
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
    operator: mesaque
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: gcr.io/apikihost/github-mesaque-k8s-v1-admin:a6ba9c239787290ac8e4698ff7832158a59e53b8
          name: admin
          ports:
            - containerPort: 80
              name: admin