apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
    operator: mesaque
    environment: prod
  name: admin
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: admin